/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SanskarIndexRouteImport } from './routes/sanskar/index'
import { Route as SanskarProposalsRouteImport } from './routes/sanskar/proposals'
import { Route as SanskarOpportunitiesRouteImport } from './routes/sanskar/opportunities'
import { Route as SanskarLeaderboardRouteImport } from './routes/sanskar/leaderboard'
import { Route as SanskarInsightsRouteImport } from './routes/sanskar/insights'
import { Route as SanskarClientsRouteImport } from './routes/sanskar/clients'
import { Route as SanskarChatbotRouteImport } from './routes/sanskar/chatbot'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanskarIndexRoute = SanskarIndexRouteImport.update({
  id: '/sanskar/',
  path: '/sanskar/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanskarProposalsRoute = SanskarProposalsRouteImport.update({
  id: '/sanskar/proposals',
  path: '/sanskar/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const SanskarOpportunitiesRoute = SanskarOpportunitiesRouteImport.update({
  id: '/sanskar/opportunities',
  path: '/sanskar/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const SanskarLeaderboardRoute = SanskarLeaderboardRouteImport.update({
  id: '/sanskar/leaderboard',
  path: '/sanskar/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SanskarInsightsRoute = SanskarInsightsRouteImport.update({
  id: '/sanskar/insights',
  path: '/sanskar/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const SanskarClientsRoute = SanskarClientsRouteImport.update({
  id: '/sanskar/clients',
  path: '/sanskar/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const SanskarChatbotRoute = SanskarChatbotRouteImport.update({
  id: '/sanskar/chatbot',
  path: '/sanskar/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/sanskar/chatbot': typeof SanskarChatbotRoute
  '/sanskar/clients': typeof SanskarClientsRoute
  '/sanskar/insights': typeof SanskarInsightsRoute
  '/sanskar/leaderboard': typeof SanskarLeaderboardRoute
  '/sanskar/opportunities': typeof SanskarOpportunitiesRoute
  '/sanskar/proposals': typeof SanskarProposalsRoute
  '/sanskar/': typeof SanskarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/sanskar/chatbot': typeof SanskarChatbotRoute
  '/sanskar/clients': typeof SanskarClientsRoute
  '/sanskar/insights': typeof SanskarInsightsRoute
  '/sanskar/leaderboard': typeof SanskarLeaderboardRoute
  '/sanskar/opportunities': typeof SanskarOpportunitiesRoute
  '/sanskar/proposals': typeof SanskarProposalsRoute
  '/sanskar': typeof SanskarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/sanskar/chatbot': typeof SanskarChatbotRoute
  '/sanskar/clients': typeof SanskarClientsRoute
  '/sanskar/insights': typeof SanskarInsightsRoute
  '/sanskar/leaderboard': typeof SanskarLeaderboardRoute
  '/sanskar/opportunities': typeof SanskarOpportunitiesRoute
  '/sanskar/proposals': typeof SanskarProposalsRoute
  '/sanskar/': typeof SanskarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/sanskar/chatbot'
    | '/sanskar/clients'
    | '/sanskar/insights'
    | '/sanskar/leaderboard'
    | '/sanskar/opportunities'
    | '/sanskar/proposals'
    | '/sanskar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/sanskar/chatbot'
    | '/sanskar/clients'
    | '/sanskar/insights'
    | '/sanskar/leaderboard'
    | '/sanskar/opportunities'
    | '/sanskar/proposals'
    | '/sanskar'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/sanskar/chatbot'
    | '/sanskar/clients'
    | '/sanskar/insights'
    | '/sanskar/leaderboard'
    | '/sanskar/opportunities'
    | '/sanskar/proposals'
    | '/sanskar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SanskarChatbotRoute: typeof SanskarChatbotRoute
  SanskarClientsRoute: typeof SanskarClientsRoute
  SanskarInsightsRoute: typeof SanskarInsightsRoute
  SanskarLeaderboardRoute: typeof SanskarLeaderboardRoute
  SanskarOpportunitiesRoute: typeof SanskarOpportunitiesRoute
  SanskarProposalsRoute: typeof SanskarProposalsRoute
  SanskarIndexRoute: typeof SanskarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanskar/': {
      id: '/sanskar/'
      path: '/sanskar'
      fullPath: '/sanskar/'
      preLoaderRoute: typeof SanskarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanskar/proposals': {
      id: '/sanskar/proposals'
      path: '/sanskar/proposals'
      fullPath: '/sanskar/proposals'
      preLoaderRoute: typeof SanskarProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanskar/opportunities': {
      id: '/sanskar/opportunities'
      path: '/sanskar/opportunities'
      fullPath: '/sanskar/opportunities'
      preLoaderRoute: typeof SanskarOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanskar/leaderboard': {
      id: '/sanskar/leaderboard'
      path: '/sanskar/leaderboard'
      fullPath: '/sanskar/leaderboard'
      preLoaderRoute: typeof SanskarLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanskar/insights': {
      id: '/sanskar/insights'
      path: '/sanskar/insights'
      fullPath: '/sanskar/insights'
      preLoaderRoute: typeof SanskarInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanskar/clients': {
      id: '/sanskar/clients'
      path: '/sanskar/clients'
      fullPath: '/sanskar/clients'
      preLoaderRoute: typeof SanskarClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanskar/chatbot': {
      id: '/sanskar/chatbot'
      path: '/sanskar/chatbot'
      fullPath: '/sanskar/chatbot'
      preLoaderRoute: typeof SanskarChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SanskarChatbotRoute: SanskarChatbotRoute,
  SanskarClientsRoute: SanskarClientsRoute,
  SanskarInsightsRoute: SanskarInsightsRoute,
  SanskarLeaderboardRoute: SanskarLeaderboardRoute,
  SanskarOpportunitiesRoute: SanskarOpportunitiesRoute,
  SanskarProposalsRoute: SanskarProposalsRoute,
  SanskarIndexRoute: SanskarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
